### ISSUE TITLE
plotly-based nwb widgets not working

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-hub#38]
NWB widgets relies pretty heavily on plotly. Currently, all the figures that rely on plotly are not showing up:

![image](https://user-images.githubusercontent.com/844306/192903298-aa7298f4-eef0-44e5-9d10-47baa44f4b7b.png)

This same code used to work as expected months ago but at some point broke on the hub side. The odd thing is that stand-alone plotly graphs do work:

```python
import plotly.express as px

fig = px.line(x=["a","b","c"], y=[1,3,2], title="sample figure")
print(fig)
fig.show()
```
![image](https://user-images.githubusercontent.com/844306/192903473-fd87162f-0757-41ad-ae3b-89c177def7d2.png)

[This thread](https://community.plotly.com/t/error-displaying-figurewidget/11974/7) suggests it might be an issue with strict package version requirements

**Comment by bendichter** [comment]
@satra now nwbwidgets is entirely broken because it doesn't work in Python 3.10 yet. See active issue [here](https://github.com/NeurodataWithoutBorders/nwbwidgets/issues/210). We can prioritize this if 3.10 is important for other reasons.

**Comment by satra** [comment]
the base jupyter datascience notebook uses 3.10. and since 3.10 has been around for a year it would be good to make it compatible. also if it doesn't work on 3.10 why did it install fine ?

i'll downgrade the jupyter base to may to move back to 3.9, but please let me know when nwbwidgets is fixed. most default installs of python now use 3.10

**Comment by bendichter** [comment]
Yeah, two of our dependencies are lagging. We've filed issues but they haven't been addressed yet. I'll see if we can find alternative solutions while they catch up.

**Comment by bendichter** [comment]
@satra I fixed our dependencies in nwbwidgets for Python 3.10 and just cut a release so we should be able to upgrade now to Python 3.10.

There have also been some advances in the packaging of plotly so it's no longer necessary to install separate extensions. From the [plotly docs](https://plotly.com/python/getting-started/), all you need to do to get it running in jupyter lab is

```
$ pip install "jupyterlab>=3" "ipywidgets>=7.6"
```

We are currently using the latest version of plotly, 5.10, along with jupyterlab 3.4 and ipywidgets 7.7, so we should be fine here.

I am now able to run nwbwidgets in a Python 3.10 env locally with plotly components working correctly if I run simply

```
conda create -n py310 python=3.10 jupyter matplotlib scipy h5py
conda activate py310
pip install nwbwidgets
```

Perhaps the issue is [here](https://github.com/dandi/dandi-hub/blob/3d2cf2c665d33354c960e0e633383d334964860d/docker/Dockerfile#L57-L58), where we are still installing the extensions `jupyterlab-plotly` and `plotlywidget`? I don't think that's necesssary with the latest version of plotly and it might be causing conflicting versions of dependencies, but honestly that's just a guess.

**Comment by satra** [comment]
could you make a release of nwbwidgets so i can rebuild the docker images with it?

**Comment by bendichter** [comment]
Yes 0.8.1 is 3.10 compatible

**Comment by satra** [comment]
ah, thanks i didn't see it in github and didn't check pypi. i see it now.

**Comment by satra** [comment]
i've published the new containers. give it a shot, and if it works please close this issue.

**Comment by satra** [comment]
@bendichter - i don't think this is still operational. i tried the demo notebook. 

```
ipywidgets                8.0.2 
nwbwidgets              0.8.1
```

<details> <summary> error details </summary>

```python
AttributeError                            Traceback (most recent call last)
Cell In [1], line 3
      1 import pynwb
      2 from pynwb import NWBHDF5IO
----> 3 from nwbwidgets import nwb2widget
      4 import requests
      6 def _search_assets(url, filepath):

File /opt/conda/lib/python3.10/site-packages/nwbwidgets/__init__.py:3
      1 import plotly.io as pio
----> 3 from .view import nwb2widget, default_neurodata_vis_spec
      5 # from .ephys_viz_interface import ephys_viz_neurodata_vis_spec
      7 from .version import version as __version__

File /opt/conda/lib/python3.10/site-packages/nwbwidgets/view.py:16
     12 from ndx_spectrum import Spectrum
     14 from .dynamictablesummary import DynamicTableSummaryWidget
---> 16 from nwbwidgets import (
     17     behavior,
     18     misc,
     19     base,
     20     ecephys,
     21     image,
     22     ophys,
     23     icephys,
     24     timeseries,
     25     file,
     26     spectrum,
     27 )
     30 # def show_dynamic_table(node: DynamicTable, **kwargs):
     31 def show_dynamic_table(node, **kwargs) -> widgets.Widget:

File /opt/conda/lib/python3.10/site-packages/nwbwidgets/behavior.py:12
      9 from pynwb import TimeSeries
     10 from pynwb.behavior import SpatialSeries, BehavioralEvents
---> 12 from nwbwidgets import base
     14 from .utils.timeseries import (
     15     get_timeseries_tt,
     16     get_timeseries_in_units,
     17     timeseries_time_to_ind,
     18 )
     19 from .timeseries import (
     20     AlignMultiTraceTimeSeriesByTrialsConstant,
     21     AlignMultiTraceTimeSeriesByTrialsVariable,
   (...)
     24     SeparateTracesPlotlyWidget,
     25 )

File /opt/conda/lib/python3.10/site-packages/nwbwidgets/base.py:8
      5 import pandas as pd
      6 import matplotlib.pyplot as plt
----> 8 import ipysheet
      9 from IPython import display
     10 from ipywidgets import widgets

File /opt/conda/lib/python3.10/site-packages/ipysheet/__init__.py:2
      1 from ._version import version_info, __version__
----> 2 from .sheet import Cell, Range, Sheet, Renderer
      3 from .easy import *
      4 from .pandas_loader import from_dataframe, to_dataframe

File /opt/conda/lib/python3.10/site-packages/ipysheet/sheet.py:14
      9 from ._version import __version_js__
     11 semver_range_frontend = "~" + __version_js__
---> 14 @widgets.register('ipysheet.Cell')
     15 class Cell(widgets.Widget):
     16     _model_name = Unicode('CellRangeModel').tag(sync=True)
     17     _model_module = Unicode('ipysheet').tag(sync=True)

File /opt/conda/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:264, in register(widget)
    262 def register(widget):
    263     """A decorator registering a widget class in the widget registry."""
--> 264     w = widget.class_traits()
    265     Widget._widget_types.register(w['_model_module'].default_value,
    266                                  w['_model_module_version'].default_value,
    267                                  w['_model_name'].default_value,
   (...)
    270                                  w['_view_name'].default_value,
    271                                  widget)
    272     return widget

AttributeError: 'str' object has no attribute 'class_traits'
```
</details>

**Comment by bendichter** [comment]
Ah ok this is an issue with ipywidgets 8. I'll try to track that down as well

**Comment by bendichter** [comment]
I will work on fixing ipywidgets 8.0 compatibility but I'm not quite sure why we are having this problem to begin with. ipysheet  requires ipywidgets<8.0,>=7.5.0, and specifies this, so nwbwidgets should install with ipywidgets-7.6.5. This is the behavior I get on my fresh local environment and it installs and runs with no problem.

**Comment by bendichter** [comment]
The latest release of nwbwidgets, 0.9.0, should fix the issue with ipywidgets 8.0. I don't know if it will fix the plotly issue though because I have not been able to reproduce it locally

**Comment by satra** [comment]
there are many additional dependencies in the hub. so something else could install a version greater than 8. i'll trigger a rebuild via nwbwidgets version

**Comment by satra** [comment]
i'm having a really difficult time installing nwbwidgets inside the jupyter datascience container.  try using this container: `jupyter/datascience-notebook:2022-09-27`

**Comment by satra** [comment]
the primary source of conflict i think comes from ipydatagrid.

**Comment by satra** [comment]
for the moment i'm pinning ipydatagrid to current master.

**Comment by bendichter** [comment]
ipysheets is incompatible with ipywidgets 8.0. One of the developers recommended [ipydatagrid](https://github.com/NeurodataWithoutBorders/nwbwidgets/issues/210#issuecomment-1262248744) as an alternative, since all we really need is to draw a table, not change any of the values. This is the only new dependency of nwbwidgets 9.0, so yes I think you are right this must be causing the problems. I'm checking that container now..

**Comment by bendichter** [comment]
@satra how do I run jupyter with that container?

**Comment by satra** [comment]
`docker run -it --rm -p 8888 jupyter/datascience-notebook:2022-09-27` and then go to `localhost:8888` or `docker run -it --rm -p 8888 --entrypoint bash jupyter/datascience-notebook:2022-09-27` to get a terminal.

also looks like everything got installed fine  on the hub with changing to master branch.

**Comment by bendichter** [comment]
Not sure if you meant to run this on my own computer or on the hub. On my computer I get the standard notebook startup messages in the terminal:

```bash
(base) MacBook-Pro-7:~ bendichter$ docker run -it --rm jupyter/datascience-notebook:2022-09-27
Entered start.sh with args: jupyter lab
Executing the command: jupyter lab
[I 2022-10-02 13:42:11.990 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-10-02 13:42:11.996 ServerApp] nbclassic | extension was successfully linked.
[I 2022-10-02 13:42:11.997 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2022-10-02 13:42:12.114 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-10-02 13:42:12.124 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-10-02 13:42:12.125 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.10/site-packages/jupyterlab
[I 2022-10-02 13:42:12.125 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2022-10-02 13:42:12.127 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-10-02 13:42:12.129 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-10-02 13:42:12.130 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2022-10-02 13:42:12.130 ServerApp] Jupyter Server 1.18.1 is running at:
[I 2022-10-02 13:42:12.130 ServerApp] http://eac1f9ba4b05:8888/lab?token=67a5e6782fe318734757cb2e5eeb59a79331cd270b8a2286
[I 2022-10-02 13:42:12.130 ServerApp]  or http://127.0.0.1:8888/lab?token=67a5e6782fe318734757cb2e5eeb59a79331cd270b8a2286
[I 2022-10-02 13:42:12.130 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-10-02 13:42:12.131 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-7-open.html
    Or copy and paste one of these URLs:
        http://eac1f9ba4b05:8888/lab?token=67a5e6782fe318734757cb2e5eeb59a79331cd270b8a2286
     or http://127.0.0.1:8888/lab?token=67a5e6782fe318734757cb2e5eeb59a79331cd270b8a2286
```

but when I go to localhost:8888 I get "This site cannot be reached"

<img width="713" alt="image" src="https://user-images.githubusercontent.com/844306/193457260-59d011e9-a7a2-4187-ac5b-eac1a0a950f9.png">

On the hub I get

```
jovyan@jupyter-bendichter:~$ docker run -it --rm jupyter/datascience-notebook:2022-09-27
bash: docker: command not found
```

**Comment by satra** [comment]
There is a -p flag in the docker command that was missed.

**Comment by bendichter** [comment]
Ah, sorry it didn't work the first time so I was playing around with the flags. `docker run -it --rm -p 8888 jupyter/datascience-notebook:2022-09-27` and `docker run -it --rm -p 8888 --entrypoint bash jupyter/datascience-notebook:2022-09-27` had the same behavior.

**Comment by satra** [comment]
Sorry the format I gave is incorrect. It should be 8888:8888

**Comment by bendichter** [comment]
I see what you mean with ipydatagrid. It's not really essenial, so I have removed that as a dependency for now until they release a version that supports ipywidgets 8.0. Could you try building again with the latest version on nwbwidgets, 0.9.1?

**Comment by satra** [comment]
There current containers on the hub should work as they are built with the
master version of ipydatagrid that includes support for ioywidgets 8. Day
you want to try that out before I rebuild again.

**Comment by bendichter** [comment]
OK, it's running, but we are still having the issue with plotly FigureWidgets. I don't think the latest version of nwbwidgets will fix that though.

**Comment by bendichter** [comment]
@satra Here's the key comment: https://github.com/plotly/plotly.py/issues/3686#issuecomment-1249477078

plotly is not yet compatible with ipywidgets 8.0 and no one is currently working on it 😬 . Is there another package that requires this?

To be specific, heres the problem:

This is what it looks like locally:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/844306/193610624-aec2f89c-8108-4652-b736-74c67e4958cf.png">

And this is what it looks like on the server:

![image](https://user-images.githubusercontent.com/844306/192903298-aa7298f4-eef0-44e5-9d10-47baa44f4b7b.png)


The problem is specifically with the FigureWidget object. Use plotly without FigureWidget works just fine:

```python
import plotly.express as px

fig = px.line(x=["a","b","c"], y=[1,3,2], title="sample figure")
print(fig)
fig.show()
```
![image](https://user-images.githubusercontent.com/844306/192903473-fd87162f-0757-41ad-ae3b-89c177def7d2.png)


If I try to run FigureWidget on its own:

<img width="977" alt="image" src="https://user-images.githubusercontent.com/844306/193613456-5af5ad9b-3d3f-4689-9f90-95ef5fa72c67.png">

**Comment by satra** [comment]
i think this is now resolved on the hub. it had to do with a conflict between jupyter_bokeh and plotly dependencies and differences between mamba and pip installs.

**Comment by bendichter** [comment]
confirmed, it is working as expected now!
